export enum TICKET_HISTORY_ACTION_ENUM {
  CREATE = 'CREATE',
  ADD_ASSIGNEE = 'ADD_ASSIGNEE',
  CHANGE_ASSIGNEE = 'CHANGE_ASSIGNEE',
  REMOVE_ASSIGNEE = 'REMOVE_ASSIGNEE',
  UPDATE_STATUS = 'UPDATE_STATUS',
  UPDATE_POINTS = 'UPDATE_POINTS',
  UPDATE_DUE_DATE = 'UPDATE_DUE_DATE',
  DELETE = 'DELETE',
}
